version: '3'
services:
  job-assistant:
    image: psvishnu/job-assistant:v1
    # build:  # Development purpose only
    #   context: .
    #   dockerfile: Dockerfile
    expose: 
        - "8601"
    ports: 
        - "8601:8601"
    volumes:
      - .:/app
    env_file:
      - .env
    # environment:  Alternative to env_file option
    #   - OPENAI_API_KEY=your_api_key_here
    command: streamlit run app.py --server.port 8601 --client.caching True 
